name: dart_codegen_sample
description: Dart codegen sample
version: 0.0.1-dev
homepage: https://github.com/PlugFox/dart_codegen_sample.git

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  # Models
  freezed_annotation: ^0.11.0+1
  json_annotation: ^3.0.1
  meta: ^1.2.2

  # Network
  dio: ^3.0.10
  retrofit: ^1.3.4

dev_dependencies:
  test: ^1.15.3
  json_serializable: ^3.4.0
  retrofit_generator: ^1.3.7+5
  build_runner: ^1.10.1
  grinder: ^0.8.5
  freezed: ^0.11.5